NAACL award

diff --git a/bin/publish b/bin/publish
--- a/bin/publish
+++ b/bin/publish
@@ -1,12 +1,26 @@
 #!/usr/bin/env bash
 
-website_repo_path='/Users/maharshi/Documents/GitHub/maharshi95.github.io'
+commit_message=${1:-"Updated website"}
+
+website_repo_path="$HOME/GitHub/maharshi95.github.io/"
 
 echo "bundle exec jekyll build --lsi"
 bundle exec jekyll build --lsi
 
 echo "cp -r _site/* $website_repo_path"
 cp -r _site/* "$website_repo_path/"
+
+echo "Changing directory to $website_repo_path"
+cd "$website_repo_path"
+
+git add .
+git commit -m "$commit_message"
+git push origin main
+if [ $? -ne 0 ]; then
+    echo "Error: Failed to push changes to GitHub."
+    exit 1
+fi
+echo "Changes pushed to GitHub successfully."
 
 echo "Exiting.."
 exit 0
